name: dartez
description: A flutter package which provides the functionalities to play around with tezos dApps
version: 2.0.2
homepage: https://github.com/Tezsure/Dartez
repository: https://github.com/Tezsure/Dartez
issue_tracker: https://github.com/Tezsure/Dartez/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.6
  blake2b: ^0.2.2
  bs58check: ^1.0.2
  convert: ^3.0.1
  crypto: ^3.0.0
  ed25519_hd_key: ^2.2.0
  sodium_libs: ^2.1.0+1
  sodium: ^2.1.0
  http: ">=0.13.4 <2.0.0"
  js: ^0.6.3
  secp256k1: ^0.3.0
  unorm_dart: ^0.2.0
  bip32: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  glob: ^2.1.1
  path: ^1.8.2
  dependency_validator: ^3.0.0
